#' @title viewCityMap
#' 
#' @description A function that allows users to create a map of a city in the
#' United States and its surrounding area using Stamen Maps.
#' 
#' @param city_name The name of the city being mapped
#' @param state_abb The abbreviation of the state that the city is in. (e.g. 
#' New York = "NY")
#' 
#' @details Maps are generated by using package ggmap to pull map data from 
#' Stamen Maps
#' 
#' D. Kahle and H. Wickham. ggmap: Spatial Visualization with ggplot2. The R 
#' Journal, 5(1), 144-161. 
#' URL <http://journal.r-project.org/archive/2013-1/kahle-wickham.pdf>
#' 
#' US city data comes from the simplemaps United States Cities Database
#' <https://simplemaps.com/data/us-cities>
#' 
#' @importFrom ggmap get_stamenmap ggmap 
#' @importFrom ggplot2 geom_point geom_label labs aes
#' @import shiny
#' 
#' @export viewCityMap

viewCityMap <- function(city_name, state_abb){
  
  # First, we pull data for the city in question from the uscitydata data set:
  citydata <- uscitydata[uscitydata$city_ascii == city_name,-16]
  citydata <- citydata[citydata$state_id == state_abb,]
  
  # Next, we make note of the latitude, longitude, and population of the city:
  latitude <- citydata[1, 'lat']
  longitude <- citydata[1, 'lng']
  population <- citydata[1, 'population']
  
  # Then, we use the latitude and longitude to create a bounding box that 
  # ggmap can read to create the bounds of our map:
  citybbox <- c(bottom = latitude - .5,
                top = latitude + .5,
                right = longitude + .5, 
                left = longitude - .5)
  
  # Finally, we use ggmap to pull the map data from Stamen Maps and use ggmap
  # and ggplot2 to plot the map and display extra information about the city:
  citymap <- get_stamenmap(bbox = citybbox, maptype = "toner-hybrid")
  
  plot <- 
    # Plots the map
    ggmap(citymap) + 
    
    # Plots a point where the city is located
    geom_point(aes(x = longitude, y = latitude), 
               color = "red", 
               size = 3) + 
    
    # Plots a label for the city that shows the population
    geom_label(aes(x = longitude, y = latitude + .075), 
               color = "red",
               label = paste0(city_name, ", ", state_abb, "\n", 
                             "Population: ", population), size = 3) + 
    
    # Renames axes
    labs(x = "Longitude", 
         y = "Latitude")
  
  # return(plot)
  plot(plot)
}

#' ShinyApp
#'
#' @return returns the Shiny App
#' @export myApp
#'
myApp <- function(){
  shiny::runApp(appDir = system.file( "app", package="viewCityMap"))
  }

