#' @title viewCityMap
#' 
#' @description A function that allows users to create a map of a city in the
#' United States and its surrounding area using Stamen Maps.
#' 
#' @param city_name The name of the city being mapped
#' @param state The name of the state that the city is in
#' @param map_type The format of map you would like to render. Default is 
#' "toner-hybrid." Available options: "terrain", "terrain-background", 
#' "terrain-labels", "terrain-lines", "toner", "toner-2010", "toner-2011", 
#' "toner-background", "toner-hybrid", "toner-labels", "toner-lines", 
#' "toner-lite", "watercolor"
#' 
#' @details Maps are generated by using package ggmap to pull map data from 
#' Stamen Maps
#' 
#' D. Kahle and H. Wickham. ggmap: Spatial Visualization with ggplot2. The R 
#' Journal, 5(1), 144-161. 
#' URL <http://journal.r-project.org/archive/2013-1/kahle-wickham.pdf>
#' 
#' US city data comes from the simplemaps United States Cities Database
#' <https://simplemaps.com/data/us-cities>
#' 
#' @examples viewCityMap("Phoenix", "Arizona") 
#' viewCityMap("New York", "New York", "watercolor") 
#' viewCityMap("Boston", "Massachusetts", "toner") 
#' viewCityMap("Florence", "Arizona", "terrain")
#' 
#' @importFrom ggmap get_stamenmap ggmap 
#' @importFrom ggplot2 geom_point geom_label labs aes
#' @import shiny
#' 
#' @export viewCityMap

viewCityMap <- function(city_name, state, map_type = "toner-hybrid"){
  
  # First, we pull data for the city in question from the uscitydata data set:
  citydata <- uscitydata[uscitydata$city_ascii == city_name,-16]
  citydata <- citydata[citydata$state_name == state,]
  
  # Next, we make note of the latitude, longitude, and population of the city:
  latitude <- citydata[1, 'lat']
  longitude <- citydata[1, 'lng']
  population <- citydata[1, 'population']
  
  # Then, we use the latitude and longitude to create a bounding box that 
  # ggmap can read to create the bounds of our map:
  citybbox <- c(bottom = latitude - .5,
                top = latitude + .5,
                right = longitude + .5, 
                left = longitude - .5)
  
  # Finally, we use ggmap to pull the map data from Stamen Maps and use ggmap
  # and ggplot2 to plot the map and display extra information about the city:
  citymap <- ggmap::get_stamenmap(bbox = citybbox, maptype = map_type)
  
  plot <- 
    # Plots the map
    ggmap::ggmap(citymap) + 
    
    # Plots a point where the city is located
    ggplot2::geom_point(ggplot2::aes(x = longitude, y = latitude), 
               color = "red", 
               size = 3) + 
    
    # Plots a label for the city that shows the population
    ggplot2::geom_label(ggplot2::aes(x = longitude, y = latitude + .075), 
               color = "red",
               label = paste0(city_name, ", ", state, "\n", 
                             "Population: ", population), size = 3) + 
    
    # Renames axes
    labs(x = "Longitude", 
         y = "Latitude")
  
  # return(plot)
  plot(plot)
}

#' ShinyApp
#'
#' @return returns the Shiny App
#' @export myApp
#'
myApp <- function(){
  shiny::runApp(appDir = system.file( "app", package="viewCityMap"))
  }

